### ISSUE TITLE
Shows unverified even after verifying email

### ISSUE THREAD

**Issue by RJ722** [zhcet-amu/zhcet-web#294]
When logging in for the first time after verifying the email address, it shows the following warning messages (Screenshot attached):
- "Password not changed"
- "Email not verified"

Not just this, the 2FA page also isn't accessible until you log out and log back in again.
![screen shot 2019-02-10 at 9 33 07 pm](https://user-images.githubusercontent.com/15556382/52536573-5b2a2d80-2d82-11e9-834d-2f8ba45d7449.png)

**Comment by iamareebjamal** [comment]
Duplicate of #217
