### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by iamareebjamal** [zhcet-amu/zhcet-web#77]
![zhcet-logo](https://user-images.githubusercontent.com/3874064/31470052-e090b1f2-af01-11e7-9c6f-50090358ce05.png)

![zhcet-logo2](https://user-images.githubusercontent.com/3874064/31470141-391c86fc-af02-11e7-9284-8e6b8a079150.png)

**Comment by iamareebjamal** [comment]
![diagram2](https://user-images.githubusercontent.com/3874064/31855080-ec30e7f4-b6c0-11e7-92d4-f849baae6d13.png)

**Comment by RJ722** [comment]
What did you use to create these wireframes?

**Comment by iamareebjamal** [comment]
@RJ722  IntelliJ IDEA

**Comment by RJ722** [comment]
Wow! It indeed is powerful 😉
