### ISSUE TITLE
Add documentation for features and roadmap

### ISSUE THREAD

**Issue by iamareebjamal** [zhcet-amu/zhcet-web#84]
Add documentation for features and roadmap

**Comment by 0x48piraj** [comment]
On it !

**Comment by 0x48piraj** [comment]
Any flies, examples, templates for reference ?

**Comment by iamareebjamal** [comment]
Basically, we have to enlist the features of the server, and what is to be done in future. This is limited to our college, hence I guess this issue can't be handled by anyone outside our circle. Sorry :(

If you have knowledge of Spring Boot, you can enlist those features present in the server, and we'll be happy to merge those changes
